export namespace NotificationActions {
  export const ACTION_NONE = "ACTION_NONE";

  export const ACTION_CONNECTION_REQUEST_ACCEPTED = "ACTION_CONNECTION_REQUEST_ACCEPTED";
  export const ACTION_CONNECTION_REQUEST_REJECTED = "ACTION_CONNECTION_REQUEST_REJECTED";
  export const ACTION_CONNECTION_REQUEST_SENT = "ACTION_CONNECTION_REQUEST_SENT";
  export const ACTION_CONNECTION_REQUEST_RECEIVED = "ACTION_CONNECTION_REQUEST_RECEIVED";
  export const ACTION_RELATIONSHIP_UPDATED = "ACTION_RELATIONSHIP_UPDATED";
}
