name: app
description: The Positive +1 application.
publish_to: "none"
version: 3.1.0+1

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependency_overrides:
  macos_ui:
    git:
      url: https://github.com/Mayb3Nots/macos_ui
      ref: ef51bfe

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  permission_handler: ^10.2.0
  local_auth: ^2.1.6
  event_bus: ^2.0.0
  flutter_local_notifications: ^15.1.0+1
  universal_platform: 1.0.0+1
  tuple: ^2.0.1
  synchronized: ^3.1.0
  collection: ^1.17.1
  rxdart: ^0.27.7
  infinite_scroll_pagination: ^3.2.0
  flutter_secure_storage: ^8.0.0

  # Backend
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  firebase_messaging: ^14.6.0
  firebase_crashlytics: ^3.3.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.0
  google_sign_in: ^6.1.0
  mixpanel_flutter: ^2.1.1
  freerasp: ^6.1.0

  stream_chat_flutter: ^6.4.0
  stream_chat_persistence: ^6.4.0
  algolia: ^1.1.2
  google_ml_kit: ^0.16.1

  # Routing and View Management
  auto_route: ^7.7.0

  # Logging and Tracing
  logger: ^1.3.0
  device_info_plus: ^9.0.2

  # UI and Localization
  unicons: ^2.1.1
  flutter_svg: ^2.0.5
  sliver_tools: ^0.2.10
  intl: ^0.18.0
  smooth_page_indicator: ^1.1.0
  flutter_markdown: ^0.6.15+1
  html2md: ^1.3.0
  fluent_validation: ^2.1.1
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  calendar_date_picker2: ^0.5.2
  fast_cached_network_image: ^1.2.0
  image_picker: ^1.0.0
  shimmer: ^3.0.0
  expandable: ^5.0.1
  banner_carousel: ^1.2.1
  entry: ^0.0.8+1
  adaptive_dialog: ^1.9.0-0
  boxy: ^2.0.9

  # Mapping
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  google_maps_webservice: 0.0.20-nullsafety.5

  # Other
  camerawesome: ^1.4.0
  path_provider: ^2.0.15
  transparent_image: ^2.0.1
  open_settings_plus: ^0.1.0
  package_info_plus: ^4.0.2
  profanity_filter: ^2.0.0
  very_good_infinite_list: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Analysis
  flutter_lints: ^2.0.1
  riverpod_lint: ^1.3.2
  import_sorter: ^4.6.0
  custom_lint: ^0.4.0

  # Metaprogramming
  spider: ^4.2.1
  build_runner: ^2.4.4
  auto_route_generator: ^7.2.0
  json_serializable: ^6.6.2
  riverpod_generator: ^2.2.3

  # State Management
  freezed: ^2.3.4
  mocktail: ^0.3.0

  # UI
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  background_image: "assets/icons/launcher_bg.png"
  image: "assets/icons/launcher_fg.png"
  fullscreen: true

  android_12:
    image: "assets/icons/launcher_fg.png"
    color: "#FFFFFF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "assets/icons/launcher_bg.png"
  adaptive_icon_foreground: "assets/icons/launcher_fg.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/mocks/
    - assets/images/svg/
    - assets/images/png/
    - assets/maps/

  fonts:
    - family: BN
      fonts:
        - asset: assets/fonts/BN/BNSuper-Sized.otf

    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/AlbertSans/AlbertSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AlbertSans/AlbertSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlbertSans/AlbertSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlbertSans/AlbertSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans/AlbertSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlbertSans/AlbertSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlbertSans/AlbertSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlbertSans/AlbertSans-BlackItalic.ttf
          weight: 900
          style: italic
