name: ppoa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State and Modeling
  get_it: 7.2.0
  async_redux: 17.0.0
  freezed_annotation: 2.1.0
  json_annotation: 4.7.0

  # Backend
  firebase_core: 1.24.0

  # Routing and View Management
  auto_route: 5.0.1
  device_preview: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Analysis
  flutter_lints: 2.0.1
  import_sorter: 4.6.0

  # State and Modelling
  freezed: 2.1.1
  build_runner: 2.2.1
  json_serializable: 6.4.1

  # Testing
  ppo_package_test:
    path: ../../packages/ppo_package_test

flutter:
  uses-material-design: true
