// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOW62VSX_kgFJgzbqsE4vihq-fQYkLQU',
    appId: '1:1058436764613:web:a1a27234e73b4b56c2b1ac',
    messagingSenderId: '1058436764613',
    projectId: 'positiveplusone-production',
    authDomain: 'positiveplusone-production.firebaseapp.com',
    storageBucket: 'positiveplusone-production.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2KIARx9JvWKVek99FIMnh4U7xWfO_C8',
    appId: '1:1058436764613:android:744a0dbd9daed50cc2b1ac',
    messagingSenderId: '1058436764613',
    projectId: 'positiveplusone-production',
    storageBucket: 'positiveplusone-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT6zjuBRamH5wvQUDHKHS4ChTLEhzfths',
    appId: '1:1058436764613:ios:fca7fcd38dd3d1c8c2b1ac',
    messagingSenderId: '1058436764613',
    projectId: 'positiveplusone-production',
    storageBucket: 'positiveplusone-production.appspot.com',
    androidClientId: '1058436764613-l64bi96m8ukidit69hc6s2m1m2mdigkr.apps.googleusercontent.com',
    iosClientId: '1058436764613-en7rig1a3nsqp2clu6c20oju6p8a5h4v.apps.googleusercontent.com',
    iosBundleId: 'com.positiveplusone.v3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT6zjuBRamH5wvQUDHKHS4ChTLEhzfths',
    appId: '1:1058436764613:ios:fca7fcd38dd3d1c8c2b1ac',
    messagingSenderId: '1058436764613',
    projectId: 'positiveplusone-production',
    storageBucket: 'positiveplusone-production.appspot.com',
    androidClientId: '1058436764613-l64bi96m8ukidit69hc6s2m1m2mdigkr.apps.googleusercontent.com',
    iosClientId: '1058436764613-en7rig1a3nsqp2clu6c20oju6p8a5h4v.apps.googleusercontent.com',
    iosBundleId: 'com.positiveplusone.v3',
  );
}
