name: ppo_package_domain
description: Domain layer models and data manipulation for Positive Plus One
version: 0.0.1
publish_to: none
homepage: www.positiveplusone.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # State and Management
  inqvine_core_main: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:

